# This file provides instructions for packaging.

@prefix : <http://ontologi.es/doap-deps#> .

<http://purl.org/NET/cpan-uri/dist/HTTP-Link-Parser/project>
	:test-requirement       [ :on "Test::More 0.96"^^:CpanId ] ;
	:runtime-requirement    [ :on "perl 5.010"^^:CpanId ] ;
	:runtime-requirement    [ :on "HTTP::Message"^^:CpanId ] ;
	:runtime-requirement    [ :on "URI"^^:CpanId ] ;
	:runtime-requirement    [ :on "URI::Escape"^^:CpanId ] ;
	:test-recommendation    [ :on "Test::More 0.61"^^:CpanId ] ;
	:runtime-suggestion     [ :on "RDF::Trine 0.135"^^:CpanId ] .
